# using node alpine as base image
FROM node:alpine

# working dir ./app
WORKDIR /app

# Copy the package.json
# COPY ./package.json .
# COPY ./client/public .
# COPY ./src /app/src
COPY /package.json .

# Install the dependencies
RUN npm install

# Copy the server and ethereum module
COPY . .

# set the default command
CMD ["npm","start"]